
package javaClient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Hotel", targetNamespace = "http://appSOAP/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Hotel {


    /**
     * 
     * @param arg0
     * @return
     *     returns javaClient.Chambre
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getChambre", targetNamespace = "http://appSOAP/", className = "javaClient.GetChambre")
    @ResponseWrapper(localName = "getChambreResponse", targetNamespace = "http://appSOAP/", className = "javaClient.GetChambreResponse")
    @Action(input = "http://appSOAP/Hotel/getChambreRequest", output = "http://appSOAP/Hotel/getChambreResponse")
    public Chambre getChambre(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
